# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 649a64485151890a2c0d032cb3433c86f0a3205683209fbdb9b8f0469edd854d72e84c76a988e8756e80a76ca5c4a3a6fd37c1d40c9379001fe062bd52f3317c

test:
  secret_key_base: e5d932a3dabb7eadb753ca76e1c0d4ef725f63814229b28b7e4c8fb289d4d081e6f0bc0183a836c182279862c7434039f140dc8612f285293decd8ba252c8271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
